In [1]:
import numpy as np

In [2]:
x = np.array([[1,0,0],[0,0,1],[1,0,1],[1,1,0]])
y = np.array([[0],[0],[0],[1]])

In [3]:
print(x)

[[1 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]]


In [4]:
print(y)

[[0]
 [0]
 [0]
 [1]]


In [12]:
## Assign Weights
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [13]:
### Weighted Sum
sum = np.dot(x,weights) + 0.02   ## (0.02 = bias)
sum

array([[0.79132064],
       [0.65364823],
       [1.42496888],
       [0.81207259]])

In [14]:
### Activation Function
yp = 1 / (1 + np.exp(-sum))
yp

array([[0.68811483],
       [0.65783211],
       [0.8061162 ],
       [0.69255099]])

In [15]:
yp.round()

array([[1.],
       [1.],
       [1.],
       [1.]])