Numpy
* It stands for Numerical Python which can be used to do mathematical and scientific operations on multidimentional array (collection of data of same data type)
* pip install numpy

In [1]:
!pip install numpy   ## to run - shift + enter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy as np

In [3]:
### Create an array

In [5]:
a1 = np.array([1,2,3,4,5])   ## 1d array
a2 = np.array([[1,2,3,4,5]])  ## 2d array
a3 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])   ## 2d array
a4 = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]) ## 3d array
a5 = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],    ## 3d array
                [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])

In [8]:
print(len(a1))
print(len(a2))
print(len(a3))
print(len(a4))
print(len(a5))

5
1
3
1
2


In [10]:
a2  ## 2d array - single element will be 1d array

array([[1, 2, 3, 4, 5]])

In [11]:
a3

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
a4   ## 3d array - single element will be 2d array

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [13]:
a5

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [14]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)
print(a5.ndim)

1
2
2
3
3


In [15]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)

int64
int64
int64
int64
int64


In [16]:
a6 = np.array([1,2,3,4,5,4.5]) 
a6

array([1. , 2. , 3. , 4. , 5. , 4.5])

In [17]:
a6.dtype

dtype('float64')

In [20]:
a7 = np.array([1,2,3,4,5,"Umang","NSS IIT Roorkee"]) 
a7

array(['1', '2', '3', '4', '5', 'Umang', 'NSS IIT Roorkee'], dtype='<U21')

In [24]:
a7.dtype

dtype('<U21')

In [25]:
a7.ndim

1

In [26]:
### Array Operations

In [36]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([11,12,13,14,15])
op1 = np.add(a1,a2)
op2 = np.subtract(a1,a2)
op3 = np.multiply(a1,a2)
op4 = np.divide(a1,a2)
op5 = np.dot(a1,a2)

In [28]:
op1

array([12, 14, 16, 18, 20])

In [29]:
op2

array([-10, -10, -10, -10, -10])

In [31]:
op3

array([11, 24, 39, 56, 75])

In [33]:
op4

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333])

In [34]:
op5

205

In [40]:
a1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
a2 = np.array([[11,12,13,14,15],[11,12,13,14,15]])
op1 = np.add(a1,a2)
op2 = np.subtract(a1,a2)
op3 = np.multiply(a1,a2)
op4 = np.divide(a1,a2)
op5 = np.dot(a1,a2.T)

In [41]:
op5

array([[205, 205],
       [205, 205]])

In [44]:
op3

array([[11, 24, 39, 56, 75],
       [11, 24, 39, 56, 75]])

In [45]:
a1 = np.array([1,2,3,4,5])   ## 1d array
a2 = np.array([[1,2,3,4,5]])  ## 2d array
a3 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])   ## 2d array
a4 = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]) ## 3d array
a5 = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],    ## 3d array
                [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])

In [46]:
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)
print(a5.shape)

(5,)
(1, 5)
(3, 5)
(1, 3, 5)
(2, 3, 5)


In [49]:
### Random Numbers

In [55]:
r1 = np.random.randint(100)  ## 0 to 99
r1

73

In [62]:
np.random.seed(10)   ## 0 to 2**32 -1
r1 = np.random.randint(100)  ## 0 to 99
r1

9

In [64]:
r1 = np.random.randint(100,500)  ## 100 to 499
r1

115

In [65]:
r1 = np.random.randint(100,500,10)  ## 10 numbers between 100 to 499
r1

array([420, 469, 223, 256, 321, 469, 108, 173, 356, 140])

In [66]:
r1 = np.random.randint(100,500,(5,3))  ## 5x3 array between 100 to 499
r1

array([[471, 116, 456],
       [339, 495, 154],
       [444, 463, 222],
       [162, 133, 300],
       [456, 277, 279]])

In [69]:
np.random.seed(10) 
r1 = np.random.randint(100,500,(5,3,5))  ## 5x3x5 array between 100 to 499
r1

array([[[365, 225, 115, 420, 469],
        [223, 256, 321, 469, 108],
        [173, 356, 140, 471, 116]],

       [[456, 339, 495, 154, 444],
        [463, 222, 162, 133, 300],
        [456, 277, 279, 154, 177]],

       [[113, 343, 482, 241, 448],
        [442, 386, 258, 189, 240],
        [421, 131, 413, 392, 383]],

       [[118, 193, 177, 194, 348],
        [495, 256, 174, 316, 493],
        [115, 118, 218, 171, 444]],

       [[495, 245, 235, 303, 384],
        [389, 350, 452, 144, 233],
        [104, 171, 444, 444, 406]]])

In [70]:
### Array Indexing and Slicing

In [72]:
np.random.seed(10) 
r1 = np.random.randint(1,50,(8,6))
r1

array([[10, 37, 16,  1, 29, 26],
       [30, 49, 30,  9, 10,  1],
       [43, 41, 37, 17, 37, 48],
       [12, 25, 44, 34,  9, 37],
       [15, 14,  6, 14, 26, 14],
       [29, 23, 31, 31, 26, 13],
       [ 2, 32, 37, 28, 19, 30],
       [14, 23, 24, 31, 12, 29]])

In [73]:
len(r1)

8

In [74]:
r1[0]

array([10, 37, 16,  1, 29, 26])

In [75]:
r1[7]

array([14, 23, 24, 31, 12, 29])

In [76]:
r1[-1]

array([14, 23, 24, 31, 12, 29])

In [77]:
r1[7,2]

24

In [78]:
r1[7][2]

24

In [79]:
r1[:,:]   ## rows,cols

array([[10, 37, 16,  1, 29, 26],
       [30, 49, 30,  9, 10,  1],
       [43, 41, 37, 17, 37, 48],
       [12, 25, 44, 34,  9, 37],
       [15, 14,  6, 14, 26, 14],
       [29, 23, 31, 31, 26, 13],
       [ 2, 32, 37, 28, 19, 30],
       [14, 23, 24, 31, 12, 29]])

In [80]:
r1[2:6,:]

array([[43, 41, 37, 17, 37, 48],
       [12, 25, 44, 34,  9, 37],
       [15, 14,  6, 14, 26, 14],
       [29, 23, 31, 31, 26, 13]])

In [81]:
r1[2:,:]

array([[43, 41, 37, 17, 37, 48],
       [12, 25, 44, 34,  9, 37],
       [15, 14,  6, 14, 26, 14],
       [29, 23, 31, 31, 26, 13],
       [ 2, 32, 37, 28, 19, 30],
       [14, 23, 24, 31, 12, 29]])

In [82]:
r1[:5,:]  ## start to 4

array([[10, 37, 16,  1, 29, 26],
       [30, 49, 30,  9, 10,  1],
       [43, 41, 37, 17, 37, 48],
       [12, 25, 44, 34,  9, 37],
       [15, 14,  6, 14, 26, 14]])

In [83]:
r1[:5] 

array([[10, 37, 16,  1, 29, 26],
       [30, 49, 30,  9, 10,  1],
       [43, 41, 37, 17, 37, 48],
       [12, 25, 44, 34,  9, 37],
       [15, 14,  6, 14, 26, 14]])

In [84]:
r1

array([[10, 37, 16,  1, 29, 26],
       [30, 49, 30,  9, 10,  1],
       [43, 41, 37, 17, 37, 48],
       [12, 25, 44, 34,  9, 37],
       [15, 14,  6, 14, 26, 14],
       [29, 23, 31, 31, 26, 13],
       [ 2, 32, 37, 28, 19, 30],
       [14, 23, 24, 31, 12, 29]])

In [85]:
r1[:,2:5]

array([[16,  1, 29],
       [30,  9, 10],
       [37, 17, 37],
       [44, 34,  9],
       [ 6, 14, 26],
       [31, 31, 26],
       [37, 28, 19],
       [24, 31, 12]])

In [86]:
r1[2:5:,2:5]

array([[37, 17, 37],
       [44, 34,  9],
       [ 6, 14, 26]])

In [92]:
r1

array([[10, 37, 16,  1, 29, 26],
       [30, 49, 30,  9, 10,  1],
       [43, 41, 37, 17, 37, 48],
       [12, 25, 44, 34,  9, 37],
       [15, 14,  6, 14, 26, 14],
       [29, 23, 31, 31, 26, 13],
       [ 2, 32, 37, 28, 19, 30],
       [14, 23, 24, 31, 12, 29]])

In [88]:
r1[2,3]

17

In [91]:
r1[2][3]

17