In [ ]:
import numpy as np
n1 = np.array([[3,5,2,1],[6,3,9,5],[1,7,4,8]])
print(n1)

[[3 5 2 1]
 [6 3 9 5]
 [1 7 4 8]]


In [ ]:
n1.ravel()

array([3, 5, 2, 1, 6, 3, 9, 5, 1, 7, 4, 8])

In [ ]:
n1.flatten()

array([3, 5, 2, 1, 6, 3, 9, 5, 1, 7, 4, 8])

* Matrix multiplications

In [ ]:
print(n1)

[[3 5 2 1]
 [6 3 9 5]
 [1 7 4 8]]


In [ ]:
n2 = np.array([[2,5,5,1],
               [3,8,9,2]])
print(n2)

[[2 5 5 1]
 [3 8 9 2]]


In [ ]:
np.transpose(n2)

array([[2, 3],
       [5, 8],
       [5, 9],
       [1, 2]])

In [ ]:
np.dot(n1,np.transpose(n2))

array([[ 42,  69],
       [ 77, 133],
       [ 65, 111]])

In [ ]:
#3x + 2y + z = 5
#x + y + z = 7
#5x + 7y + 3z = 9

In [ ]:
A = np.array([[3,2,1],[1,1,1],[5,7,3]])
print(A)

[[3 2 1]
 [1 1 1]
 [5 7 3]]


In [ ]:
X = np.array([['x'],['y'],['z']])
print(X)

[['x']
 ['y']
 ['z']]


In [ ]:
B = np.array([[5],[7],[9]])
print(B)

[[5]
 [7]
 [9]]


In [ ]:
#A.X = B
#X = A_inv.B

In [ ]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.66666667 -0.16666667 -0.16666667]
 [-0.33333333 -0.66666667  0.33333333]
 [-0.33333333  1.83333333 -0.16666667]]


In [ ]:
X = np.dot(A_inv,B)
print(X)

[[ 0.66666667]
 [-3.33333333]
 [ 9.66666667]]


In [ ]:
np.dot(A,X)

array([[5.],
       [7.],
       [9.]])

In [ ]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
n1 = np.array([[3,5,2,1],[6,3,9,5],[1,7,4,8]])
print(n1)

[[3 5 2 1]
 [6 3 9 5]
 [1 7 4 8]]


In [ ]:
n3 = n1[1:3,1:3].copy()
print(n3)

[[3 9]
 [7 4]]


In [ ]:
n3[1,1] = 44

In [ ]:
print(n3)

[[ 3  9]
 [ 7 44]]


In [ ]:
print(n1)

[[3 5 2 1]
 [6 3 9 5]
 [1 7 4 8]]
