**Numpy - Numerical Python**

In [ ]:
a = 7
b = 3
print(a/b)

2.3333333333333335


In [ ]:
c = [10,20,30,40,50,60,70]
print(c/2)

TypeError: ignored

In [ ]:
divide_by_two = lambda x : [val/2 for val in x]
divide_by_two(c)

[5.0, 10.0, 15.0, 20.0, 25.0, 30.0, 35.0]

In [ ]:
d = [[10,20,30,40,50,60,70],[11,22,33,44,55,66,77],[101,202,303,404,505,606,707]]
print(d)

[[10, 20, 30, 40, 50, 60, 70], [11, 22, 33, 44, 55, 66, 77], [101, 202, 303, 404, 505, 606, 707]]


In [ ]:
import numpy as np
n1 = np.array([10,20,30,40,50,60,70])
print(n1)

[10 20 30 40 50 60 70]


In [ ]:
print(type(n1))

<class 'numpy.ndarray'>


In [ ]:
print(n1/2)
print(n1*3)

[ 5. 10. 15. 20. 25. 30. 35.]
[ 30  60  90 120 150 180 210]


In [ ]:
n2 = np.array([[10,20,30,40,50,60,70],[11,22,33,44,55,66,77],[101,202,303,404,505,606,707]])
print(n2)

[[ 10  20  30  40  50  60  70]
 [ 11  22  33  44  55  66  77]
 [101 202 303 404 505 606 707]]


In [ ]:
print(n2.shape)
print(n2.ndim)
print(n2.size)

(3, 7)
2
21


In [ ]:
print(np.sum(n2))
print(np.prod(n2))
print(np.mean(n2))
print(np.median(n2))
print(np.std(n2))
print(np.min(n2))
print(np.max(n2))
print(np.argmax(n2))
print(np.argmin(n2))

3416
8876945796898488320
162.66666666666666
60.0
207.41156080497433
10
707
20
0


In [ ]:
#axis = 1:- Calculations will be made on each row
print(np.sum(n2 , axis = 1))
print(np.prod(n2, axis = 1))
print(np.mean(n2, axis = 1))
print(np.median(n2, axis = 1))
print(np.std(n2, axis = 1))
print(np.min(n2, axis = 1))
print(np.max(n2, axis = 1))
print(np.argmax(n2, axis = 1))
print(np.argmin(n2, axis = 1))

[ 280  308 2828]
[       50400000000        98215341840 540356217461933040]
[ 40.  44. 404.]
[ 40.  44. 404.]
[ 20.  22. 202.]
[ 10  11 101]
[ 70  77 707]
[6 6 6]
[0 0 0]


In [ ]:
#axis = 0:- Calculations will be made on each column
print(np.sum(n2 , axis = 0))
print(np.prod(n2, axis = 0))
print(np.mean(n2, axis = 0))
print(np.median(n2, axis = 0))
print(np.std(n2, axis = 0))
print(np.min(n2, axis = 0))
print(np.max(n2, axis = 0))
print(np.argmax(n2, axis = 0))
print(np.argmin(n2, axis = 0))

[122 244 366 488 610 732 854]
[  11110   88880  299970  711040 1388750 2399760 3810730]
[ 40.66666667  81.33333333 122.         162.66666667 203.33333333
 244.         284.66666667]
[11. 22. 33. 44. 55. 66. 77.]
[ 42.66406242  85.32812484 127.99218726 170.65624968 213.3203121
 255.98437452 298.64843694]
[10 20 30 40 50 60 70]
[101 202 303 404 505 606 707]
[2 2 2 2 2 2 2]
[0 0 0 0 0 0 0]


In [ ]:
print(n2)

[[ 10  20  30  40  50  60  70]
 [ 11  22  33  44  55  66  77]
 [101 202 303 404 505 606 707]]


In [ ]:
np.where(n2 == 33)

(array([1]), array([2]))

In [ ]:
#array + range = creating an array using a range
n3 = np.arange(0,36)
print(n3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [ ]:
#Change the shape of an array => reshape
#36 => (1,36),(36,1),(2,18),(18,2),(3,12),(12,3),(4,9),(9,4),(6,6)

n4 = n3.reshape(6,6)
print(n4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
#n-dimensional array into 1 dimensional
print(n4.ravel())
print(n4.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [ ]:
#Accesiing any value
print(n4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
print(n4[0])
print(n4[3])

[0 1 2 3 4 5]
[18 19 20 21 22 23]


In [ ]:
print(n4[0,3])
print(n4[3,2])

3
20


In [ ]:
#Slicing in an array
print(n4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
n4[: , :]    #array[row slicing , column slicing]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
n4[: , 1:3]   #array[intial index : intial index + num of rows or columns]

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [ ]:
n4[: , 1:2]

array([[ 1],
       [ 7],
       [13],
       [19],
       [25],
       [31]])

In [ ]:
n4[2:5 ,:]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
print(n4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
print(n4[1:5 , 1:5])

[[ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]
 [25 26 27 28]]
