In [ ]:
import pandas as pd
import numpy as np

In [ ]:
n1 = np.array([[3,5,2,1],[6,3,9,5],[1,7,4,8]],dtype=float)
print(n1)

[[3. 5. 2. 1.]
 [6. 3. 9. 5.]
 [1. 7. 4. 8.]]


In [ ]:
n1[0,0] = 4.2

In [ ]:
print(n1)

[[4.2 5.  2.  1. ]
 [6.  3.  9.  5. ]
 [1.  7.  4.  8. ]]


In [ ]:
n1[0,0] = '5'
print(n1)

[[5. 5. 2. 1.]
 [6. 3. 9. 5.]
 [1. 7. 4. 8.]]


In [ ]:
d1 = pd.DataFrame(n1)             #converting numpy array into a pandas data frame
d1.columns = ['a','b','c','d']
d1.index = [1,2,3]
d1

a    b    c    d
1  5.0  5.0  2.0  1.0
2  6.0  3.0  9.0  5.0
3  1.0  7.0  4.0  8.0

In [ ]:
d1.a

1    5.0
2    6.0
3    1.0
Name: a, dtype: float64

In [ ]:
d1['a']

1    5.0
2    6.0
3    1.0
Name: a, dtype: float64

In [ ]:
d1[['a','c']]

a    c
1  5.0  2.0
2  6.0  9.0
3  1.0  4.0

In [ ]:
d1.dtypes

a    float64
b    float64
c    float64
d    float64
dtype: object

In [ ]:
d1['b'] = d1['b'].astype(int)     #astype() - used to convert type of a data column

In [ ]:
d1

a  b    c    d
1  5.0  5  2.0  1.0
2  6.0  3  9.0  5.0
3  1.0  7  4.0  8.0

In [ ]:
d1.dtypes

a    float64
b      int64
c    float64
d    float64
dtype: object

In [ ]:
print(type(d1))
print(type(d1.b))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


* Numpy array are homogeneous
* Pandas column or pandas series are homogeneous

In [ ]:
details = {'name' : ['Abhay' , 'Vijay' , 'John' , 'Jacob' , 'Jerry'],
           'Salary' : ['$3000' , '$2545' , '$2000' , '$40000' , '$50000'],
           'exp' : [2.4 , 4.3, 5.5, 6.2 , 7.9]}
print(details)

{'name': ['Abhay', 'Vijay', 'John', 'Jacob', 'Jerry'], 'Salary': ['$3000', '$2545', '$2000', '$40000', '$50000'], 'exp': [2.4, 4.3, 5.5, 6.2, 7.9]}


In [ ]:
d2 = pd.DataFrame(details)
d2

NameError: ignored

In [ ]:
d2['age'] = [40, 30, 35 , 45 , 50]

In [ ]:
loc = ['Delhi', 'Indore','Hyderabaad' , 'Chennai' , 'Mumbai']
d2.insert(1,'Location',loc)

In [ ]:
d2

name    Location   Salary  exp  age
0  Abhay       Delhi   3000.0  2.4   40
1  Vijay      Indore   2545.0  4.3   30
2   John  Hyderabaad   2000.0  5.5   35
3  Jacob     Chennai  40000.0  6.2   45
4  Jerry      Mumbai  50000.0  7.9   50

In [ ]:
d2.dtypes

name       object
Salary     object
exp       float64
age         int64
dtype: object

In [ ]:
#to replace a string value in a data column => str.replace()
d2['Salary'] = d2['Salary'].str.replace('$','').astype(float)

<ipython-input-147-691bb1e5a5f9>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  d2['Salary'] = d2['Salary'].str.replace('$','').astype(float)


In [ ]:
d2

name   Salary  exp  age
0  Abhay   3000.0  2.4   40
1  Vijay   2545.0  4.3   30
2   John   2000.0  5.5   35
3  Jacob  40000.0  6.2   45
4  Jerry  50000.0  7.9   50

In [ ]:
d2.dtypes

name       object
Salary    float64
exp       float64
age         int64
dtype: object

In [ ]:
d3 = pd.DataFrame(details)
d3

name  Salary  exp
0  Abhay   $3000  2.4
1  Vijay   $2545  4.3
2   John   $2000  5.5
3  Jacob  $40000  6.2
4  Jerry  $50000  7.9

In [ ]:
def fix_salary(x):       #user defined function
  return int(x[1:])

In [ ]:
fix_salary('$3000')

3000

In [ ]:
#to iterate a user defined function on a data column => apply()
d3['Salary'].apply(fix_salary)

0     3000
1     2545
2     2000
3    40000
4    50000
Name: Salary, dtype: int64

In [ ]:
d3['Salary'].apply(lambda x : int(x[1:]))

0     3000
1     2545
2     2000
3    40000
4    50000
Name: Salary, dtype: int64

In [ ]:
d2

name   Salary  exp  age
0  Abhay   3000.0  2.4   40
1  Vijay   2545.0  4.3   30
2   John   2000.0  5.5   35
3  Jacob  40000.0  6.2   45
4  Jerry  50000.0  7.9   50

**Titanic Passengers Data**

In [ ]:
df = pd.read_csv('/content/titanic_train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df.shape

(891, 12)

* data filtering

In [ ]:
#unique() - return unique category in a data column
print(df['Survived'].unique())
print(df['Pclass'].unique())
print(df['Sex'].unique())

[0 1]
[3 1 2]
['male' 'female']


In [ ]:
#value_counts() - return number of times a category is present
print(df['Survived'].value_counts())
print(df['Pclass'].value_counts())
print(df['Sex'].value_counts())

0    549
1    342
Name: Survived, dtype: int64
3    491
1    216
2    184
Name: Pclass, dtype: int64
male      577
female    314
Name: Sex, dtype: int64


In [ ]:
#Seperate all survived and non survived passengers
print((df['Survived'] == 0).sum())
print((df['Survived'] == 1).sum())

549
342


In [ ]:
#Passengers who can't survived
dfs0 = df[df['Survived'] == 0]
dfs0.head()

PassengerId  Survived  Pclass                            Name   Sex   Age  \
0            1         0       3         Braund, Mr. Owen Harris  male  22.0   
4            5         0       3        Allen, Mr. William Henry  male  35.0   
5            6         0       3                Moran, Mr. James  male   NaN   
6            7         0       1         McCarthy, Mr. Timothy J  male  54.0   
7            8         0       3  Palsson, Master. Gosta Leonard  male   2.0   

   SibSp  Parch     Ticket     Fare Cabin Embarked  
0      1      0  A/5 21171   7.2500   NaN        S  
4      0      0     373450   8.0500   NaN        S  
5      0      0     330877   8.4583   NaN        Q  
6      0      0      17463  51.8625   E46        S  
7      3      1     349909  21.0750   NaN        S

In [ ]:
#Passengers who survived.
dfs1 = df[df['Survived'] == 1]
dfs1.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [ ]:
#All Female Passengers
df_female=df[df['Sex']=='female']
df_female.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [ ]:
#Seperate and store passengers with age value more then 25
df25 = df[df['Age'] > 25]
df25.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
6            7         0       1   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
6      0             17463  51.8625   E46        S

In [ ]:
#Seperate all Passengers travelling in class 2 & class 3
dfclass2_3 = df[(df['Pclass'] == 2) | (df['Pclass'] == 3)]
dfclass2_3.head()

PassengerId  Survived  Pclass                            Name     Sex  \
0            1         0       3         Braund, Mr. Owen Harris    male   
2            3         1       3          Heikkinen, Miss. Laina  female   
4            5         0       3        Allen, Mr. William Henry    male   
5            6         0       3                Moran, Mr. James    male   
7            8         0       3  Palsson, Master. Gosta Leonard    male   

    Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0  22.0      1      0         A/5 21171   7.2500   NaN        S  
2  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4  35.0      0      0            373450   8.0500   NaN        S  
5   NaN      0      0            330877   8.4583   NaN        Q  
7   2.0      3      1            349909  21.0750   NaN        S

In [ ]:
#inin() => to compare more then 1 condition as or
df[df['Pclass'].isin([2,3])]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[675 rows x 12 columns]

In [ ]:
(df['Pclass'] == 2).sum()

184

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df['totalPassenger'] = df['SibSp'] + df['Parch'] + 1

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  totalPassenger  
0      0         A/5 21171   7.2500   NaN        S               2  
1      0          PC 17599  71.2833   C85        C               2  
2      0  STON/O2. 3101282   7.9250   NaN        S               1  
3      0            113803  53.1000  C123        S               2  
4      0            373450   8.0500   NaN        S               1

In [ ]:
df['totalPassenger'].value_counts()

1     537
2     161
3     102
4      29
6      22
5      15
7      12
11      7
8       6
Name: totalPassenger, dtype: int64

In [ ]:
df['totalPassenger'].sum()    #Total number of Passengers

1697

In [ ]:
len(df)             #Total number of bookings

891

* Null values in a data frame

In [ ]:
df.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age               177
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin             687
Embarked            2
totalPassenger      0
dtype: int64

In [ ]:
#drop the rows having missing values in Embarked
#dropna() - to drop a row or column with missing value

df1 = df.dropna(axis='rows' , subset = ['Embarked'])
df1.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  totalPassenger  
0      0         A/5 21171   7.2500   NaN        S               2  
1      0          PC 17599  71.2833   C85        C               2  
2      0  STON/O2. 3101282   7.9250   NaN        S               1  
3      0            113803  53.1000  C123        S               2  
4      0            373450   8.0500   NaN        S               1

In [ ]:
df1.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age               177
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin             687
Embarked            0
totalPassenger      0
dtype: int64

In [ ]:
#drop the cabin column with almost 80% missing values
#drop() - to drop a specific column or row

df2 = df1.drop('Cabin' , axis='columns')
df2.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  totalPassenger  
0      0         A/5 21171   7.2500        S               2  
1      0          PC 17599  71.2833        C               2  
2      0  STON/O2. 3101282   7.9250        S               1  
3      0            113803  53.1000        S               2  
4      0            373450   8.0500        S               1

In [ ]:
df2.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age               177
SibSp               0
Parch               0
Ticket              0
Fare                0
Embarked            0
totalPassenger      0
dtype: int64

In [ ]:
#Use average age value to fill missing spaces  in age column
print(df['Age'].mean())

29.69911764705882


In [ ]:
df2['Age'] = df2['Age'].fillna(29.70)     #fillna() - to fill the blank space or missing value with a value

In [ ]:
df2.isnull().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age               0
SibSp             0
Parch             0
Ticket            0
Fare              0
Embarked          0
totalPassenger    0
dtype: int64