In [1]:
import numpy as np

In [2]:
x = np.array([[1,0,0],[0,0,1],[1,0,1],[1,1,0]])
y = np.array([[0],[0],[0],[1]])

In [3]:
print(x)

[[1 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]]


In [4]:
print(y)

[[0]
 [0]
 [0]
 [1]]


In [5]:
## Assign Weights
np.random.seed(10)
weights = np.random.random((3,1))
weights

array([[0.77132064],
       [0.02075195],
       [0.63364823]])

In [6]:
### Weighted Sum
sum = np.dot(x,weights) + 0.02   ## (0.02 = bias)
sum

array([[0.79132064],
       [0.65364823],
       [1.42496888],
       [0.81207259]])

In [7]:
### Activation Function
yp = 1 / (1 + np.exp(-sum))
yp

array([[0.68811483],
       [0.65783211],
       [0.8061162 ],
       [0.69255099]])

In [8]:
yp.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [9]:
#a = np.where(yp>=0.7,1,0)
#a

In [18]:
### Gradient Descent & Back Propagation (Optimize Model)
sum = np.dot(x,weights) + 0.02
yp = 1 / (1 + np.exp(-sum))
error = y - yp
change_in_weight = error * yp * (1-yp)
weights = weights + np.dot(x.T,change_in_weight)
error

array([[-0.54118349],
       [-0.45409956],
       [-0.49024821],
       [ 0.39802112]])

In [14]:
x.T.shape

(3, 4)

In [13]:
change_in_weight.shape

(4, 1)

In [20]:
### Training
for i in range(1000):
  sum = np.dot(x,weights) + 0.02
  yp = 1 / (1 + np.exp(-sum))
  error = y - yp
  change_in_weight = error * yp * (1-yp)
  weights = weights + np.dot(x.T,change_in_weight)

In [21]:
error

array([[-0.04175677],
       [-0.02310484],
       [-0.00100921],
       [ 0.03392967]])

In [22]:
yp

array([[0.04175677],
       [0.02310484],
       [0.00100921],
       [0.96607033]])

In [23]:
yp.round()

array([[0.],
       [0.],
       [0.],
       [1.]])

In [24]:
weights

array([[-3.15379975],
       [ 6.48329912],
       [-3.76485964]])